/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/projects': typeof ProjectsRoute
  '/api/chat': typeof ApiChatRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case-studies' | '/projects' | '/api/chat' | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case-studies' | '/projects' | '/api/chat' | '/work/$slug'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/projects'
    | '/api/chat'
    | '/work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiChatRoute: typeof ApiChatRoute
  WorkSlugRoute: typeof WorkSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ProjectsRoute: ProjectsRoute,
  ApiChatRoute: ApiChatRoute,
  WorkSlugRoute: WorkSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
